   ((nil .  ((currentProject . "TheoryOfComputation")
             (cov-lcov-file-name . '("./coverage/lcov.info"))
             (eval . (when (or (not (string= (easysession-get-current-session-name) "TheoryOfComputation")) (not (boundp 'initproject)))
                       (binky-restore "~/.emacs.d/binky/cache/TheoryOfComputation")))
             (eval . (setq initproject nil))
             (eval . (binky-save "~/.emacs.d/binky/cache/TheoryOfComputation"))
             (eval . (add-hook 'kill-emacs-hook #'(lambda () (binky-save "~/.emacs.d/binky/cache/TheoryOfComputation"))  nil t))
             (eval . (add-hook 'kill-emacs-hook #'(lambda () (makunbound 'initproject))  nil t))
             (inferior-lisp-pyrogram . "/nix/store/w432l3gnb8zj6438k4yhjh4qyd5hhmcf-sbcl-2.4.4/bin/sbcl")
             (eval . (if (not (assoc 'TheoryOfComputation session-alist-format))
                         (add-to-list 'session-alist-format '(TheoryOfComputation  .   "Learning the ways of Turing"))
                       ()))
             (eval . (cond ((not (member "TheoryOfComputation" (easysession--get-all-names))) (easysession-save-as "TheoryOfComputation"))
                           ((not (string= (easysession-get-current-session-name) "TheoryOfComputation")) (easysession-switch-to "TheoryOfComputation"))
                           (t ()))))))
